# Generated by Django 4.2.4 on 2023-08-31 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('path', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurantmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('description', models.TextField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('restaurant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='content', to='base.restaurant')),
            ],
        ),
    ]
