# Generated by Django 4.2.4 on 2023-09-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_restaurantmenu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurantmenu',
            name='price',
            field=models.IntegerField(),
        ),
    ]
