# Generated by Django 4.2.4 on 2023-09-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
