# Generated by Django 4.2.4 on 2023-09-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_restaurantmenu_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
