# Generated by Django 4.2.4 on 2023-09-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='dish',
            new_name='dishid',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
