# Generated by Django 4.2.4 on 2023-09-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_shippingaddress_state_alter_shippingaddress_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='itemsprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
    ]
