# Generated by Django 4.2.4 on 2023-09-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_itemsprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='itemsprice',
            new_name='itemsPrice',
        ),
    ]
