# Generated by Django 4.2.4 on 2023-09-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_itemsprice_order_itemsprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
